### ISSUE TITLE
Somethings up with my rating i dont understand. 

### ISSUE THREAD

**Issue by apoorva-a98** [mathscapes/DecodeVector#19]
i split up my problems but the rating has reached 396. What?

**Comment by indirectjump** [comment]
@vineetarath Can you have a look?

**Comment by vineetarath** [comment]
Hey @apoorva-a98 !

Refer https://github.com/mathscapes/DecodeVector/wiki/Vineeta

The new system needs you to fill in all these fields:
Date | D | T | L | P | S | Rating | Problems solved

NOTE: The number on the left of 'problems solved' indicates whether the problem is a 1 pt, 2pt or 3 pt one.

_________________________________________________________________________________________________________
Use the formula by which our rating is normally calculated:

5+2D−T/(L+1)+S
where,

D is the number of days you’ve solved at least one PSET problem,
T is the total number of days since your date of join,
L is your current level,
S is the sum of points accumulated by solving PSET problems.

**Comment by apoorva-a98** [comment]
i think i have done that. could you check? is it because i haven't added for the days i didn't upload?

**Comment by vineetarath** [comment]
Hi @apoorva-a98 , simran and i intend to screen through your rating system information as well as your pset qns around 4 pm today. Until then, can you update your rating system day wise - irrespective of problems solved - it'll help us track the issue with your rating calculation
